ALTER TABLE public.rodizio 
  ADD COLUMN IF NOT EXISTS marca text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS serie text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS dot text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS modelo text NOT NULL DEFAULT '';